-- MySQL Script generated by MySQL Workbench
-- Wed Aug 19 16:23:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`player` (
  `player_id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(45) NOT NULL,
  `birthday` DATETIME NOT NULL,
  PRIMARY KEY (`player_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`game_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`game_type` (
  `game_type_id` INT NOT NULL,
  `game_type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`game_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`game` (
  `game_id` INT NOT NULL,
  `game_type` VARCHAR(45) NOT NULL,
  `game_link` VARCHAR(45) NOT NULL,
  `game_name` VARCHAR(45) NOT NULL,
  `game_type_game_type_id` INT NOT NULL,
  PRIMARY KEY (`game_id`),
  INDEX `fk_game_game_type1_idx` (`game_type_game_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_game_game_type1`
    FOREIGN KEY (`game_type_game_type_id`)
    REFERENCES `mydb`.`game_type` (`game_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`game_score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`game_score` (
  `game_score_id` INT NOT NULL,
  `score` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `player_player_id` INT NOT NULL,
  `game_game_id` INT NOT NULL,
  PRIMARY KEY (`game_score_id`),
  INDEX `fk_game_score_player_idx` (`player_player_id` ASC) VISIBLE,
  INDEX `fk_game_score_game1_idx` (`game_game_id` ASC) VISIBLE,
  CONSTRAINT `fk_game_score_player`
    FOREIGN KEY (`player_player_id`)
    REFERENCES `mydb`.`player` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_score_game1`
    FOREIGN KEY (`game_game_id`)
    REFERENCES `mydb`.`game` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
